### ISSUE TITLE
Cannot download ZX Spectrum Covers

### ISSUE THREAD

**Issue by dogfacedboyuk1** [andiweli/hexflow-covers#7]
Retroflow cannot download ZX Spectrum covers on my Vita, it only finds 2 game covers (Cookie and Chequered Flag). If you look in the retro covers section on github, these two games are named cookie.png and chequered flag.png along with an additional duplicate files using the normal naming convention with company in brackets. So basically its just detecting these two .png s and ignoring everything else. I have manually downloaded all covers and put them in the correct folder in retroflow and after rescanning it does not detect any of them. Any ideas on this problem?

**Comment by Andiweli** [comment]
Please head over to https://github.com/jimbob4000/RetroFlow-Launcher 
This is just the cover-archive.
