### ISSUE TITLE
Attached cover update pack for PS Vita

### ISSUE THREAD

**Issue by jimbob4000** [andiweli/hexflow-covers#9]
Hi again,

Hope you're well.

I've attached a PS Vita cover pack to bring the repo up to date with the ones I added for RetroFlow (mostly covers for ports).
There shouldn't be any duplicates if you decide to add them.

Thanks

[PSVita Cover Updates Apr 2024.zip](https://github.com/andiweli/hexflow-covers/files/15081315/PSVita.Cover.Updates.Apr.2024.zip)

**Comment by andiweli** [comment]
Hey thereSure no problem, just a small flu here😂Will upload tomorrow. Regards, AndreasAm 23.04.2024 um 20:38 schrieb jimbob4000 ***@***.***>:﻿
Hi again,
Hope you're well.
I've attached a PS Vita cover pack to bring the repo up to date with the ones I added for RetroFlow (mostly covers for ports).
There shouldn't be any duplicates if you decide to add them.
Thanks
PSVita Cover Updates Apr 2024.zip

**Comment by Andiweli** [comment]
Done! Thanks :)
